# Generated by Django 4.2 on 2023-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.EmailField(max_length=20),
        ),
    ]
